name: "Build legacy Nix package on Ubuntu"

on:
  push:

strategy:
  matrix:
    os:
      - ubuntu-latest
      - macos-latest

runs-on: ${{ matrix.os }}

jobs:

  build:
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Building default package
        run: nix build .

  check:
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Running checks
        run: nix check .
